### ISSUE TITLE
After I make transactions what happen next

### ISSUE THREAD

**Issue by Dalton2500** [ton-blockchain/wallet-contract#54]
After I make transactions what happen next

**Comment by Ans075** [comment]
https://github.com/ton-blockchain/wallet-contract/issues/54#issue-2521096836

**Comment by QuimbyJr** [comment]
Can you provide more info on your issue?

**Comment by MORTEZAMIRSALI** [comment]
We continue to cooperate in the ecosystem and help the progress of the pools

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
hola buenas soy nuevo y no sé verificar los contratos para poder cobrar

**Comment by Ans075** [comment]
I am just beginner I make account 3 year ago and my boss said it's fake you didn't receive anything after that I didn't check now I'm unemployed and don't have any source of income my friend told me about crypto mining and I deposit in web 3 wrong address checking on YouTube how to retrieve in one video indian gay said import wallet from exchange ten delete your money will go to exchange and I got in trouble if anyone was in trouble because of me I am really sorry I was in very critical condition and totally broken I want just my money back and I was don't no it creating a big issue once again sorry,😔to all how was in troubling because of me 🙏✌️

**Comment by Ans075** [comment]
am just beginner I make account 3 year ago and my boss said it's fake you didn't receive anything after that I didn't check now I'm unemployed and don't have any source of income my friend told me about crypto mining and I deposit in web 3 wrong address checking on YouTube how to retrieve in one video indian gay said import wallet from exchange ten delete your money will go to exchange and I got in trouble if anyone was in trouble because of me I am really sorry I was in very critical condition and totally broken I want just my money back and I was don't no it creating a big issue once again sorry,😔to all how was in troubling because of me 🙏✌️

**Comment by Ans075** [comment]
am just beginner I make account 3 year ago and my boss said it's fake you didn't receive anything after that I didn't check now I'm unemployed and don't have any source of income my friend told me about crypto mining and I deposit in web 3 wrong address checking on YouTube how to retrieve in one video indian gay said import wallet from exchange ten delete your money will go to exchange and I got in trouble if anyone was in trouble because of me I am really sorry I was in very critical condition and totally broken I want just my money back and I was don't no it creating a big issue once again sorry,😔to all how was in troubling because of me 🙏✌️

**Comment by Ans075** [comment]
I am just beginner I make account 3 year ago and my boss said it's fake you didn't receive anything after that I didn't check now I'm unemployed and don't have any source of income my friend told me about crypto mining and I deposit in web 3 wrong address checking on YouTube how to retrieve in one video indian gay said import wallet from exchange ten delete your money will go to exchange and I got in trouble if anyone was in trouble because of me I am really sorry I was in very critical condition and totally broken I want just my money back and I was don't no it creating a big issue once again sorry,😔to all how was in troubling because of me 🙏✌️

**Comment by Ans075** [comment]
I am just beginner I make account 3 year ago and my boss said it's fake you didn't receive anything after that I didn't check now I'm unemployed and don't have any source of income my friend told me about crypto mining and I deposit in web 3 wrong address checking on YouTube how to retrieve in one video indian gay said import wallet from exchange ten delete your money will go to exchange and I got in trouble if anyone was in trouble because of me I am really sorry I was in very critical condition and totally broken I want just my money back and I was don't no it creating a big issue once again sorry,😔to all how was in troubling because of me 🙏✌️

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
helllo
