### ISSUE TITLE
UQD6fKxcU-O542oNFAo3Sy5zVmJt_qRCXsb4l4gG9CFRANzo

### ISSUE THREAD

**Issue by Marazali75** [ton-blockchain/wallet-contract#77]
UQD6fKxcU-O542oNFAo3Sy5zVmJt_qRCXsb4l4gG9CFRANzo

**Comment by MORTEZAMIRSALI** [comment]
Hello, don't be bored, everyone, Tonkeeper, you don't intend to cooperate, because I haven't been there for several years because of problems, instead of thanking my financial resources for helping to climb the tanks, all of them have created obstacles.  Be trustworthy people, he is trying to create an obstacle to own my belongings. Friends, I have been here for some time. Tunkeeper has not only spared 1 cent from my wealth, but he has reduced all the transactions from me on AirDrabs, but all of them are a violation of this example of violation and anti-citizen rights and abuse.  Absolutely from a citizen, if these were realistic and justice-oriented, even if my children came to control my assets for 60 years, there would not have been so much mistreatment and tension between all subscribers.  Don't stop trusting and be convinced of your right

**Comment by MORTEZAMIRSALI** [comment]
You have come to this understanding better than anyone, someone who is independent in the development of reservoirs and structures and can create separate access, but I didn't touch 1 cent, I waited to see what you were doing, I saw you block, this is a violation of humanity, I warn you seriously, if you block people's property, you are fine  You know, all the reservoirs that I own are open to me, even if you bring professors from the whole world, you can't encroach on other people's property, stick to the principles and rules, if the evil doesn't end by tomorrow sunrise, the result is better, all the responsibility is on you.  No, because all of us investors came hoping for progress, it's better that you don't destroy the ecosystem

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of your wallet.
