### ISSUE TITLE
Return my money back 

### ISSUE THREAD

**Issue by Newtoncoinuser** [ton-blockchain/wallet-contract#86]
This is my address of toncoin - UQB9ypJ7MxcH7axHB4hs0qCR4RKVihsfB3nQIlA4KqMrZpLO    .     If you didn't return my money back i will fill a new case on you in cyber crime security. I will damage your all career. I know you cheated and my friend also in cyber crime . Return my money back otherwise i will take action against you .

**Comment by MORTEZAMIRSALI** [comment]
Hello, I also have the most assets in the tanks. It's gone too much. It's not clear what to do with the wallet. If you have a proof of payment, it can be traced. Tonkeeper started these issues and problems. If he had behaved normally from the beginning, we wouldn't be in this situation now.  These issues are caused by the failure of the reservoirs. Unfortunately, the ineffective new managers cause such irreparable blows to the collection, which is the reason why they ask why you were not there and did not receive your capital.  We are active. I remember when Bitcoin came, we used to write several times on the paper so as not to make a mistake. Unfortunately, Tonkeeper's managers reacted very quickly because only the account owner had come and he had not attacked.  He knows the code, when someone comes up to the reservoirs and his lessons, it means that the person owns these lessons, so maybe the person is a politician and in the field of politics, whose work of the Tonkeeper is unsightly and has gone to everyone's eyes.  No, I'm not even hacking Telegram, it's entering my privacy. I'll follow up on this matter from the American Embassy and I'll add a complaint to the complaints. You are not allowed to do such an inappropriate act. X is also in the trap of the delusional managers of Tonkeeper, they are only questioning themselves, unfortunately.  I am not a bad-natured or bad-hearted person, but also, the actions of my complaint in the international community will weaken you and the Telegram group, as he observed, on the one hand, such a case of entering my privacy and Telegram and controlling all the pages as a result.  Our documents are complete. After a few days of rest, I will appear stronger in terms of help and cooperation. I hope dear Mr. Dorlev will intervene in this matter

**Comment by Newtoncoinuser** [comment]
![Screenshot_2024_0922_060641](https://github.com/user-attachments/assets/1f058ec6-da56-4765-93bb-91509ece60e9)
This is the proof that i didn't get any dogs coin and my ton was transfer to you

**Comment by jankhan-work** [comment]
![Screenshot_20240924-221129](https://github.com/user-attachments/assets/f1cb9cef-9103-4683-86fd-a9e9ab469ca7)

**Comment by jankhan-work** [comment]
Scammer

**Comment by MORTEZAMIRSALI** [comment]
You see, I have been having problems with these for months and years. On
the one hand, they are afraid that I will convert my assets and leave.
These problems are that all my assets are being blocked by X and Tonkeeper
on the other side, and even because of uncompleted transactions, many of my
sums have been blocked. Deducting and putting in a bottleneck On the other
hand, for 1 week, Telegram took over my account, activated Russian robots
in it, entered my privacy, took all my account with a hamster until the
rest of the tokens were destroyed, after a week, allowing an empty account
to enter with Russian bots sent from Telegram, unfortunately, X has also
blocked my account, I have emailed many times, I asked and said that it is
my responsibility. What is the reason for the misbehavior and violations in
the ecosystem, which unfortunately are among the top organizations, X
entered my tonvolt without my permission and deleted all of my tonvolt, I
downloaded it again and saw that it was really empty. Taking me for their
own benefit, no organization has any accountability

در تاریخ یکشنبه ۲۹ سپتامبر ۲۰۲۴،‏ ۲۱:۰۴ Ali3219 ***@***.***>
نوشت:

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by Darlingtonmelody** [comment]
UQBEuRi14nYgnh8DUl4L_qa7Hyh_22cnTrLB8OsHnpxYm5hc
